

[kubernetes]
format = 'on [⛵ $context \($namespace\)](blue) '
disabled = false

[username]
format = "[$user]($style) "

[hostname]
ssh_only = true
format = "on [$hostname](green) "

[nodejs]
disabled = true

[golang]
disabled = true

[time]
disabled = false
format = '🕙[ $time ]($style) '

[status]
symbol = "🔴"
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false
