
[kubernetes]
format = '[$symbol$context \($namespace\)](#633c01) '
disabled = false
detect_folders = [ 'k8s' ]
detect_files = [ '.k8s' ]
symbol = "⛵"

[username]
format = "[$user](bold #0969da) "

[hostname]
ssh_only = true
format = "on [$hostname](#1a7f37) "

[directory]
style = "#0969da"

[nodejs]
disabled = true

[golang]
disabled = true

[time]
disabled = false
format = '🕙[ $time ](#0969da) '

[status]
symbol = "🔴"
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false
