gui:
  theme:
    lightTheme: false # For terminals with a light background
    selectedLineBgColor:
      - default # set to `default` to have no background colour

  git:
    paging:
      colorArg: always
      pager: delta --light --paging=never
