  # gui:
    # theme:
    #   lightTheme: true
    #   activeBorderColor:
    #     - black
    #     - bold
    #   inactiveBorderColor:
    #     - black

  git:
    paging:
      colorArg: always
      pager: delta --light --paging=never
