gui:
  theme:
    lightTheme: true # For terminals with a light background
    activeBorderColor:
      - black
      - bold
    inactiveBorderColor:
      - grey
    selectedLineBgColor:
      - default # set to `default` to have no background colour

git:
  commit:
    signOff: true
  paging:
    colorArg: always
    pager: delta --light --paging=never

os:
  editPreset: nvim

