gui:
  theme:
    lightTheme: true # For terminals with a light background
    activeBorderColor:
      - black
      - bold
    inactiveBorderColor:
      - black
    selectedLineBgColor:
      - default # set to `default` to have no background colour

  git:
    paging:
      colorArg: always
      pager: delta --light --paging=never
